#!/usr/bin/env python3
"""
Generate smart.liquid Liquid variable include for DAK IGs.

Source of truth: IG Publisher processed output directory (output/).
This script scans the IG Publisher output for FHIR resource JSON files
(matching the pattern {ResourceType}-{id}.json) and generates Liquid
variable assignments for each published resource instance.

Normalization rule: resource id is normalized for safe Liquid variable names
by replacing all non-alphanumeric characters (including '-', '.', whitespace)
with '_'.

Variable naming convention: smart__<ResourceType>__<id_normalized>__<category>__<key>
  - url__canonical  : canonical URL of the resource (url field)
  - url__page       : HTML page URL relative to IG root
  - url__json       : JSON download URL relative to IG root
  - text__display   : human-readable display label (title or name)
  - link__html      : HTML anchor element linking to the resource page
  - elements__<key> : scalar data elements (name, title, description, status, version, ...)

Usage:
    python generate_smart_liquid.py [output_dir] [ig_root]

Defaults:
    output_dir = ./output  (IG Publisher output)
    ig_root    = .         (repository root, where input/ lives)

Author: SMART Guidelines Team
"""

import hashlib
import json
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# FHIR resource types we want to expose as Liquid variables.
# Deliberately broad so new resource types are picked up automatically.
_KNOWN_RESOURCE_TYPES = {
    "ActorDefinition", "ActivityDefinition", "CapabilityStatement",
    "CodeSystem", "ConceptMap", "ExampleScenario", "GraphDefinition",
    "ImplementationGuide", "Library", "Measure", "MessageDefinition",
    "NamingSystem", "ObservationDefinition", "OperationDefinition",
    "PlanDefinition", "Questionnaire", "QuestionnaireResponse",
    "SearchParameter", "SpecimenDefinition", "StructureDefinition",
    "StructureMap", "TerminologyCapabilities", "TestPlan", "TestScript",
    "ValueSet",
}

# Scalar element keys to expose under __elements__
_ELEMENT_KEYS = [
    "name", "title", "description", "purpose", "status",
    "version", "date", "publisher", "copyright",
    "experimental", "kind", "type",
]

# Header written at the top of the generated Liquid file.
# {source_description} is replaced at generation time with details of the
# artifact used as source of truth.
_FILE_HEADER_TEMPLATE = """\
{{%- comment -%}}
  AUTO-GENERATED FILE – DO NOT EDIT MANUALLY
  Generated by: input/scripts/generate_smart_liquid.py

  Source of truth: {source_description}

  Normalization: resource id characters that are not alphanumeric are
  replaced with '_' to produce safe Liquid variable names.

  Variable naming: smart__<ResourceType>__<id_normalized>__<category>__<key>
    url__canonical   – canonical URL (url field of the resource)
    url__page        – HTML page path (e.g. StructureDefinition-Foo.html)
    url__json        – JSON download path (e.g. StructureDefinition-Foo.json)
    url__xml         – XML download path (e.g. StructureDefinition-Foo.xml)
    url__ttl         – Turtle/RDF download path (e.g. StructureDefinition-Foo.ttl)
    url__json_schema – JSON Schema path (logical models only; StructureDefinition-Foo.schema.json)
    text__display    – human-readable label (title or name)
    link__html       – HTML anchor element
    elements__*      – scalar data elements (name, title, description, …)
{{%- endcomment -%}}
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def normalize_id(resource_id: str) -> str:
    """Replace non-alphanumeric characters with '_' for safe variable names."""
    return re.sub(r'[^A-Za-z0-9]', '_', resource_id)


def var(resource_type: str, resource_id: str, *parts: str) -> str:
    """Build a smart__ variable name from components."""
    nid = normalize_id(resource_id)
    suffix = "__".join(parts)
    return f"smart__{resource_type}__{nid}__{suffix}"


def liquid_assign(variable_name: str, value: str) -> str:
    """Render a Liquid {% assign %} statement, escaping the value."""
    # Escape backslashes first, then double quotes and control characters
    escaped = (
        value
        .replace('\\', '\\\\')
        .replace('"', '\\"')
        .replace('\n', '\\n')
        .replace('\r', '\\r')
        .replace('\t', '\\t')
    )
    return f'{{% assign {variable_name} = "{escaped}" %}}'


def get_display(resource: Dict[str, Any]) -> str:
    """Return the best human-readable label for a resource."""
    for key in ("title", "name", "id"):
        val = resource.get(key)
        if val and isinstance(val, str):
            return val
    return resource.get("id", "")


def build_page_filename(resource_type: str, resource_id: str) -> str:
    """Return the conventional IG Publisher HTML filename for a resource."""
    return f"{resource_type}-{resource_id}.html"


def build_json_filename(resource_type: str, resource_id: str) -> str:
    """Return the conventional IG Publisher JSON filename for a resource."""
    return f"{resource_type}-{resource_id}.json"


def build_xml_filename(resource_type: str, resource_id: str) -> str:
    """Return the conventional IG Publisher XML filename for a resource."""
    return f"{resource_type}-{resource_id}.xml"


def build_ttl_filename(resource_type: str, resource_id: str) -> str:
    """Return the conventional IG Publisher Turtle (RDF) filename for a resource."""
    return f"{resource_type}-{resource_id}.ttl"


def build_json_schema_filename(resource_type: str, resource_id: str) -> str:
    """Return the conventional IG Publisher JSON schema filename for a logical model."""
    return f"{resource_type}-{resource_id}.schema.json"


def is_logical_model(resource: Dict[str, Any]) -> bool:
    """Return True if the resource is a StructureDefinition with kind='logical'."""
    return (
        resource.get('resourceType') == 'StructureDefinition'
        and resource.get('kind') == 'logical'
    )


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def _load_json(path: Path) -> Optional[Dict[str, Any]]:
    """Load and return a JSON file, or None on error."""
    try:
        with path.open(encoding='utf-8') as fh:
            return json.load(fh)
    except (json.JSONDecodeError, OSError):
        return None


def discover_resources_from_ig_manifest(
    output_dir: Path,
) -> Optional[Tuple[str, List[Tuple[str, str, Dict[str, Any]]]]]:
    """
    Primary discovery strategy: parse the IG Publisher-generated
    ImplementationGuide JSON manifest to find all resource instances that were
    actually included in the IG.

    The IG Publisher writes ImplementationGuide-<id>.json to output/ and that
    file's definition.resource array is the authoritative, IG Publisher-curated
    list of every instance in the guide.

    Returns a (source_description, results) tuple where results is a sorted list
    of (resource_type, resource_id, resource_dict) tuples, or None if no
    suitable IG manifest is found.
    """
    if not output_dir.is_dir():
        return None

    ig_files = sorted(
        f for f in output_dir.iterdir()
        if f.is_file()
        and f.name.startswith('ImplementationGuide-')
        and f.name.endswith('.json')
    )

    if not ig_files:
        return None

    # Use the first IG manifest file found (typically there is only one)
    ig_file = ig_files[0]
    ig_data = _load_json(ig_file)
    if ig_data is None or ig_data.get('resourceType') != 'ImplementationGuide':
        return None

    ig_id = ig_data.get('id', ig_file.stem.removeprefix('ImplementationGuide-'))
    source_description = (
        f"IG Publisher output ImplementationGuide manifest: {ig_file.name}\n"
        f"  The ImplementationGuide.definition.resource array is the authoritative\n"
        f"  list of every resource instance published in IG '{ig_id}'."
    )
    print(f"📋 Using IG manifest as source of truth: {ig_file.name}")

    resource_entries = ig_data.get('definition', {}).get('resource', [])
    print(f"   IG manifest contains {len(resource_entries)} resource reference(s)")

    results: List[Tuple[str, str, Dict[str, Any]]] = []
    missing: List[str] = []

    for entry in resource_entries:
        ref = entry.get('reference', {}).get('reference', '')
        if not ref or '/' not in ref:
            continue
        resource_type, resource_id = ref.split('/', 1)
        if resource_type not in _KNOWN_RESOURCE_TYPES:
            continue

        # Load the corresponding JSON file produced by IG Publisher
        json_file = output_dir / f"{resource_type}-{resource_id}.json"
        if not json_file.exists():
            missing.append(ref)
            print(f"  ⚠️  Manifest references {ref} but {json_file.name} not found in output/")
            continue

        data = _load_json(json_file)
        if data is None or data.get('resourceType') != resource_type:
            missing.append(ref)
            continue

        actual_id = data.get('id', resource_id)
        results.append((resource_type, actual_id, data))

    if missing:
        print(f"  ⚠️  {len(missing)} manifest reference(s) had no corresponding JSON in output/")

    # Deterministic sort: resource type, then id
    results.sort(key=lambda x: (x[0], x[1]))
    return source_description, results


def discover_resources_by_scanning(
    output_dir: Path,
) -> Tuple[str, List[Tuple[str, str, Dict[str, Any]]]]:
    """
    Fallback discovery strategy: scan output_dir for FHIR resource JSON files
    matching the IG Publisher naming convention {ResourceType}-{id}.json.

    Used only when no ImplementationGuide manifest is found (e.g. offline builds
    or custom setups that do not produce an IG resource).

    Returns a (source_description, results) tuple.
    """
    results: List[Tuple[str, str, Dict[str, Any]]] = []

    source_description = (
        f"IG Publisher output directory scan: {output_dir}\n"
        f"  (Fallback: no ImplementationGuide manifest found. Scanning for\n"
        f"   FHIR JSON files matching the pattern {{ResourceType}}-{{id}}.json.)"
    )

    if not output_dir.is_dir():
        print(f"⚠️  Output directory not found: {output_dir}")
        return source_description, results

    pattern = re.compile(r'^([A-Z][A-Za-z]+)-(.+)\.json$')

    for entry in sorted(output_dir.iterdir()):
        if not entry.is_file():
            continue
        m = pattern.match(entry.name)
        if not m:
            continue
        candidate_type, candidate_id = m.group(1), m.group(2)
        if candidate_type not in _KNOWN_RESOURCE_TYPES:
            continue

        data = _load_json(entry)
        if data is None:
            continue

        if data.get('resourceType') != candidate_type:
            continue
        actual_id = data.get('id', candidate_id)
        results.append((candidate_type, actual_id, data))

    results.sort(key=lambda x: (x[0], x[1]))
    return source_description, results


def discover_resources(output_dir: Path) -> Tuple[str, List[Tuple[str, str, Dict[str, Any]]]]:
    """
    Discover resource instances from IG Publisher output.

    Primary strategy:   parse ImplementationGuide-*.json manifest (authoritative
                        list curated by IG Publisher).
    Fallback strategy:  scan output/ for {ResourceType}-{id}.json files.

    Returns (source_description, results) where results is a sorted list of
    (resource_type, resource_id, resource_dict) tuples.
    """
    manifest_result = discover_resources_from_ig_manifest(output_dir)
    if manifest_result is not None:
        return manifest_result

    print("⚠️  No ImplementationGuide manifest found – falling back to directory scan")
    return discover_resources_by_scanning(output_dir)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def generate_assignments(
    resource_type: str,
    resource_id: str,
    resource: Dict[str, Any],
) -> List[str]:
    """Generate all Liquid assign statements for a single resource instance."""
    lines: List[str] = []

    page_file = build_page_filename(resource_type, resource_id)
    json_file = build_json_filename(resource_type, resource_id)
    xml_file = build_xml_filename(resource_type, resource_id)
    ttl_file = build_ttl_filename(resource_type, resource_id)

    # URL variables
    canonical_url = resource.get('url', '')
    lines.append(liquid_assign(var(resource_type, resource_id, 'url__canonical'), canonical_url))
    lines.append(liquid_assign(var(resource_type, resource_id, 'url__page'), page_file))
    lines.append(liquid_assign(var(resource_type, resource_id, 'url__json'), json_file))
    lines.append(liquid_assign(var(resource_type, resource_id, 'url__xml'), xml_file))
    lines.append(liquid_assign(var(resource_type, resource_id, 'url__ttl'), ttl_file))

    # JSON Schema URL (logical models only)
    if is_logical_model(resource):
        json_schema_file = build_json_schema_filename(resource_type, resource_id)
        lines.append(liquid_assign(var(resource_type, resource_id, 'url__json_schema'), json_schema_file))

    # Display text
    display = get_display(resource)
    lines.append(liquid_assign(var(resource_type, resource_id, 'text__display'), display))

    # HTML link
    link_html = f'<a href="{page_file}">{display}</a>'
    lines.append(liquid_assign(var(resource_type, resource_id, 'link__html'), link_html))

    # Data elements
    for key in _ELEMENT_KEYS:
        val = resource.get(key)
        if val is not None and isinstance(val, (str, bool, int, float)):
            lines.append(liquid_assign(
                var(resource_type, resource_id, f'elements__{key}'),
                str(val),
            ))

    return lines


def generate_liquid_content(
    resources: List[Tuple[str, str, Dict[str, Any]]],
    source_description: str = "",
) -> str:
    """Return the full content of smart.liquid."""
    header = _FILE_HEADER_TEMPLATE.format(
        source_description=source_description or "IG Publisher output directory (output/)"
    )
    sections: List[str] = [header]

    current_type: Optional[str] = None
    for resource_type, resource_id, resource in resources:
        if resource_type != current_type:
            sections.append(f"\n{{%- comment -%}} === {resource_type} === {{%- endcomment -%}}")
            current_type = resource_type
        assignments = generate_assignments(resource_type, resource_id, resource)
        sections.extend(assignments)

    return "\n".join(sections) + "\n"


def build_variable_rows(
    resource_type: str,
    resource_id: str,
    resource: Dict[str, Any],
) -> List[tuple]:
    """Return a list of (variable_name, value_str) pairs for a resource."""
    rows: List[tuple] = []
    page_file = build_page_filename(resource_type, resource_id)
    json_file = build_json_filename(resource_type, resource_id)
    xml_file = build_xml_filename(resource_type, resource_id)
    ttl_file = build_ttl_filename(resource_type, resource_id)
    display = get_display(resource)
    canonical_url = resource.get('url', '')
    link_html = f'<a href="{page_file}">{display}</a>'

    rows.append((var(resource_type, resource_id, 'url__canonical'), canonical_url))
    rows.append((var(resource_type, resource_id, 'url__page'), page_file))
    rows.append((var(resource_type, resource_id, 'url__json'), json_file))
    rows.append((var(resource_type, resource_id, 'url__xml'), xml_file))
    rows.append((var(resource_type, resource_id, 'url__ttl'), ttl_file))
    if is_logical_model(resource):
        json_schema_file = build_json_schema_filename(resource_type, resource_id)
        rows.append((var(resource_type, resource_id, 'url__json_schema'), json_schema_file))
    rows.append((var(resource_type, resource_id, 'text__display'), display))
    rows.append((var(resource_type, resource_id, 'link__html'), link_html))
    for key in _ELEMENT_KEYS:
        val = resource.get(key)
        if val is not None and isinstance(val, (str, bool, int, float)):
            rows.append((var(resource_type, resource_id, f'elements__{key}'), str(val)))
    return rows


def generate_html_page(
    resources: List[Tuple[str, str, Dict[str, Any]]],
    source_description: str = "",
) -> str:
    """
    Return a standalone HTML documentation page listing all Liquid variables
    with their resolved values.  This file is written directly to output/ so
    that it is available even though smart.liquid.md is generated after the IG
    Publisher has already run (and therefore cannot be processed by the IG
    Publisher into HTML).
    """
    rows_html: List[str] = []
    current_type: Optional[str] = None
    for resource_type, resource_id, resource in resources:
        if resource_type != current_type:
            current_type = resource_type
            rows_html.append(
                f'  <tr class="group-header"><td colspan="2"><strong>{resource_type}</strong></td></tr>'
            )
        for var_name, value in build_variable_rows(resource_type, resource_id, resource):
            esc_var = var_name.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            esc_val = value.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            rows_html.append(f'  <tr><td><code>{esc_var}</code></td><td>{esc_val}</td></tr>')

    table_body = "\n".join(rows_html)
    source_note = (source_description or "IG Publisher output directory (output/)").replace('\n', '<br>\n    ')
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Smart Liquid Variables</title>
  <style>
    body {{ font-family: sans-serif; margin: 2em; }}
    h1 {{ font-size: 1.5em; }}
    p.note {{ font-size: 0.9em; color: #555; }}
    table {{ border-collapse: collapse; width: 100%; font-size: 0.85em; }}
    th, td {{ border: 1px solid #ccc; padding: 4px 8px; text-align: left; vertical-align: top; word-break: break-all; }}
    th {{ background: #f0f0f0; }}
    tr.group-header td {{ background: #e8f4ff; font-weight: bold; padding: 4px 8px; }}
    code {{ font-size: 0.95em; }}
  </style>
</head>
<body>
  <h1>Smart Liquid Variables</h1>
  <p class="note">
    AUTO-GENERATED by <code>input/scripts/generate_smart_liquid.py</code>.<br>
    Source of truth: {source_note}<br>
    Include in any page with <code>{{% include smart.liquid %}}</code>.
  </p>
  <table>
    <thead><tr><th>Variable</th><th>Value</th></tr></thead>
    <tbody>
{table_body}
    </tbody>
  </table>
</body>
</html>
"""


def generate_markdown_table(
    resources: List[Tuple[str, str, Dict[str, Any]]],
    source_description: str = "",
) -> str:
    """Return the content of smart.liquid.md documentation page."""
    source_note = source_description or "IG Publisher output directory (output/)"
    lines: List[str] = [
        "# Smart Liquid Variables",
        "",
        "This page is auto-generated by `input/scripts/generate_smart_liquid.py`.",
        f"Source of truth: {source_note.splitlines()[0]}",
        "",
        "It lists all Liquid variables available after `{% include smart.liquid %}` is",
        "included in a page, along with their resolved values.",
        "",
        "| Variable | Value |",
        "|---|---|",
    ]

    for resource_type, resource_id, resource in resources:
        for var_name, _value in build_variable_rows(resource_type, resource_id, resource):
            lines.append(f"| {var_name} | {{{{ {var_name} }}}} |")

    lines.append("")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    # -----------------------------------------------------------------------
    # Argument handling
    # -----------------------------------------------------------------------
    output_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("output")
    ig_root = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(".")

    # -----------------------------------------------------------------------
    # DAK IG check – skip entirely if dak.json is absent
    # -----------------------------------------------------------------------
    dak_json_path = ig_root / "dak.json"
    if not dak_json_path.exists():
        print("ℹ️  dak.json not found – this is not a DAK IG. Skipping smart.liquid generation.")
        return 0

    print(f"✅ DAK IG detected (dak.json found at {dak_json_path})")
    print(f"📂 Scanning IG Publisher output: {output_dir.resolve()}")

    # -----------------------------------------------------------------------
    # Discover resources
    # -----------------------------------------------------------------------
    source_description, resources = discover_resources(output_dir)
    print(f"📋 Discovered {len(resources)} resource instance(s) from IG Publisher output")
    for rt, rid, _ in resources:
        print(f"   • {rt}/{rid}")

    if not resources:
        print("⚠️  No resources found in output directory – smart.liquid will be header-only")

    # -----------------------------------------------------------------------
    # Generate input/includes/smart.liquid
    # -----------------------------------------------------------------------
    includes_dir = ig_root / "input" / "includes"
    includes_dir.mkdir(parents=True, exist_ok=True)
    smart_liquid_path = includes_dir / "smart.liquid"

    liquid_content = generate_liquid_content(resources, source_description)
    smart_liquid_path.write_text(liquid_content, encoding='utf-8')
    liquid_bytes = len(liquid_content.encode('utf-8'))
    liquid_sha = hashlib.sha256(liquid_content.encode('utf-8')).hexdigest()
    print(f"✅ Generated: {smart_liquid_path}  ({liquid_bytes} bytes, sha256={liquid_sha[:16]}…)")

    # Echo file to build logs as required
    print("=" * 72)
    print(f"=== BEGIN {smart_liquid_path} ===")
    print(liquid_content)
    print(f"=== END {smart_liquid_path} ===")
    print("=" * 72)

    # -----------------------------------------------------------------------
    # Copy to output/smart.liquid
    # -----------------------------------------------------------------------
    if output_dir.is_dir():
        output_smart_liquid_path = output_dir / "smart.liquid"
        shutil.copy2(smart_liquid_path, output_smart_liquid_path)
        copied_sha = hashlib.sha256(output_smart_liquid_path.read_bytes()).hexdigest()
        print(f"✅ Copied to: {output_smart_liquid_path}  (sha256={copied_sha[:16]}…)")
        print(f"   ℹ️  Note: output/smart.liquid is the Liquid include for use via {{%- include smart.liquid -%}}")
    else:
        print(f"⚠️  Output directory does not exist – skipping copy to output/smart.liquid")

    # -----------------------------------------------------------------------
    # Generate output/smart.liquid.html  (standalone HTML documentation page)
    #
    # This file is generated directly to output/ because smart.liquid.md is
    # produced AFTER the IG Publisher has already run, so the IG Publisher
    # cannot process it into HTML.  By generating the HTML directly here we
    # ensure the documentation page is always available at smart.liquid.html.
    # -----------------------------------------------------------------------
    if output_dir.is_dir():
        html_content = generate_html_page(resources, source_description)
        html_path = output_dir / "smart.liquid.html"
        html_path.write_text(html_content, encoding='utf-8')
        html_bytes = len(html_content.encode('utf-8'))
        print(f"✅ Generated: {html_path}  ({html_bytes} bytes)")
    else:
        print(f"⚠️  Output directory does not exist – skipping output/smart.liquid.html")

    # -----------------------------------------------------------------------
    # Generate input/pagecontent/smart.liquid.md
    # -----------------------------------------------------------------------
    pagecontent_dir = ig_root / "input" / "pagecontent"
    pagecontent_dir.mkdir(parents=True, exist_ok=True)
    smart_md_path = pagecontent_dir / "smart.liquid.md"

    md_content = generate_markdown_table(resources, source_description)
    smart_md_path.write_text(md_content, encoding='utf-8')
    md_bytes = len(md_content.encode('utf-8'))
    print(f"✅ Generated: {smart_md_path}  ({md_bytes} bytes)")
    print(f"   ℹ️  Note: smart.liquid.md will be processed by IG Publisher on the NEXT build")

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------
    print("")
    print("📊 Summary of generated artifacts:")
    print(f"   input/includes/smart.liquid         → {liquid_bytes} bytes (Liquid include; sha256={liquid_sha[:16]}…)")
    if output_dir.is_dir():
        print(f"   output/smart.liquid                 → deployed to GitHub Pages (same content)")
        print(f"   output/smart.liquid.html            → standalone HTML documentation page")
    print(f"   input/pagecontent/smart.liquid.md   → {md_bytes} bytes (processed by IG Publisher on next build)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
