#!/usr/bin/env python3
"""
Generate smart.liquid Liquid variable include for DAK IGs.

Source of truth: IG Publisher processed output directory (output/).
This script scans the IG Publisher output for FHIR resource JSON files
(matching the pattern {ResourceType}-{id}.json) and generates Liquid
variable assignments for each published resource instance.

Normalization rule: resource id is normalized for safe Liquid variable names
by replacing all non-alphanumeric characters (including '-', '.', whitespace)
with '_'.

Variable naming convention: smart__<ResourceType>__<id_normalized>__<category>__<key>
  - url__canonical  : canonical URL of the resource (url field)
  - url__page       : HTML page URL relative to IG root
  - url__json       : JSON download URL relative to IG root
  - text__display   : human-readable display label (title or name)
  - link__html      : HTML anchor element linking to the resource page
  - elements__<key> : scalar data elements (name, title, description, status, version, ...)

Usage:
    python generate_smart_liquid.py [output_dir] [ig_root]

Defaults:
    output_dir = ./output  (IG Publisher output)
    ig_root    = .         (repository root, where input/ lives)

Author: SMART Guidelines Team
"""

import json
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# FHIR resource types we want to expose as Liquid variables.
# Deliberately broad so new resource types are picked up automatically.
_KNOWN_RESOURCE_TYPES = {
    "ActorDefinition", "ActivityDefinition", "CapabilityStatement",
    "CodeSystem", "ConceptMap", "ExampleScenario", "GraphDefinition",
    "ImplementationGuide", "Library", "Measure", "MessageDefinition",
    "NamingSystem", "ObservationDefinition", "OperationDefinition",
    "PlanDefinition", "Questionnaire", "QuestionnaireResponse",
    "SearchParameter", "SpecimenDefinition", "StructureDefinition",
    "StructureMap", "TerminologyCapabilities", "TestPlan", "TestScript",
    "ValueSet",
}

# Scalar element keys to expose under __elements__
_ELEMENT_KEYS = [
    "name", "title", "description", "purpose", "status",
    "version", "date", "publisher", "copyright",
    "experimental", "kind", "type",
]

# Header written at the top of the generated Liquid file
_FILE_HEADER = """\
{%- comment -%}
  AUTO-GENERATED FILE – DO NOT EDIT MANUALLY
  Generated by: input/scripts/generate_smart_liquid.py

  Source of truth: IG Publisher processed output directory (output/).
  All resource instances in this file were discovered by scanning output/
  for FHIR resource JSON files matching the pattern {ResourceType}-{id}.json.

  Normalization: resource id characters that are not alphanumeric are
  replaced with '_' to produce safe Liquid variable names.

  Variable naming: smart__<ResourceType>__<id_normalized>__<category>__<key>
    url__canonical  – canonical URL (url field of the resource)
    url__page       – HTML page path (e.g. StructureDefinition-Foo.html)
    url__json       – JSON download path (e.g. StructureDefinition-Foo.json)
    text__display   – human-readable label (title or name)
    link__html      – HTML anchor element
    elements__*     – scalar data elements (name, title, description, …)
{%- endcomment -%}
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def normalize_id(resource_id: str) -> str:
    """Replace non-alphanumeric characters with '_' for safe variable names."""
    return re.sub(r'[^A-Za-z0-9]', '_', resource_id)


def var(resource_type: str, resource_id: str, *parts: str) -> str:
    """Build a smart__ variable name from components."""
    nid = normalize_id(resource_id)
    suffix = "__".join(parts)
    return f"smart__{resource_type}__{nid}__{suffix}"


def liquid_assign(variable_name: str, value: str) -> str:
    """Render a Liquid {% assign %} statement, escaping the value."""
    # Escape backslashes first, then double quotes and control characters
    escaped = (
        value
        .replace('\\', '\\\\')
        .replace('"', '\\"')
        .replace('\n', '\\n')
        .replace('\r', '\\r')
        .replace('\t', '\\t')
    )
    return f'{{% assign {variable_name} = "{escaped}" %}}'


def get_display(resource: Dict[str, Any]) -> str:
    """Return the best human-readable label for a resource."""
    for key in ("title", "name", "id"):
        val = resource.get(key)
        if val and isinstance(val, str):
            return val
    return resource.get("id", "")


def build_page_filename(resource_type: str, resource_id: str) -> str:
    """Return the conventional IG Publisher HTML filename for a resource."""
    return f"{resource_type}-{resource_id}.html"


def build_json_filename(resource_type: str, resource_id: str) -> str:
    """Return the conventional IG Publisher JSON filename for a resource."""
    return f"{resource_type}-{resource_id}.json"


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def discover_resources(output_dir: Path) -> List[Tuple[str, str, Dict[str, Any]]]:
    """
    Scan output_dir for FHIR resource JSON files and return a sorted list of
    (resource_type, resource_id, resource_dict) tuples.

    Files are expected to follow the IG Publisher convention:
        {ResourceType}-{id}.json
    The file content is loaded and verified to contain matching resourceType/id.
    """
    results: List[Tuple[str, str, Dict[str, Any]]] = []

    if not output_dir.is_dir():
        print(f"⚠️  Output directory not found: {output_dir}")
        return results

    pattern = re.compile(r'^([A-Z][A-Za-z]+)-(.+)\.json$')

    for entry in sorted(output_dir.iterdir()):
        if not entry.is_file():
            continue
        m = pattern.match(entry.name)
        if not m:
            continue
        candidate_type, candidate_id = m.group(1), m.group(2)
        if candidate_type not in _KNOWN_RESOURCE_TYPES:
            continue

        try:
            with entry.open(encoding='utf-8') as fh:
                data = json.load(fh)
        except (json.JSONDecodeError, OSError):
            continue

        # Verify the JSON actually contains the expected resource type/id
        if data.get('resourceType') != candidate_type:
            continue
        actual_id = data.get('id', candidate_id)

        results.append((candidate_type, actual_id, data))

    # Deterministic sort: resource type, then id
    results.sort(key=lambda x: (x[0], x[1]))
    return results


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def generate_assignments(
    resource_type: str,
    resource_id: str,
    resource: Dict[str, Any],
) -> List[str]:
    """Generate all Liquid assign statements for a single resource instance."""
    lines: List[str] = []

    page_file = build_page_filename(resource_type, resource_id)
    json_file = build_json_filename(resource_type, resource_id)

    # URL variables
    canonical_url = resource.get('url', '')
    lines.append(liquid_assign(var(resource_type, resource_id, 'url__canonical'), canonical_url))
    lines.append(liquid_assign(var(resource_type, resource_id, 'url__page'), page_file))
    lines.append(liquid_assign(var(resource_type, resource_id, 'url__json'), json_file))

    # Display text
    display = get_display(resource)
    lines.append(liquid_assign(var(resource_type, resource_id, 'text__display'), display))

    # HTML link
    link_html = f'<a href="{page_file}">{display}</a>'
    lines.append(liquid_assign(var(resource_type, resource_id, 'link__html'), link_html))

    # Data elements
    for key in _ELEMENT_KEYS:
        val = resource.get(key)
        if val is not None and isinstance(val, (str, bool, int, float)):
            lines.append(liquid_assign(
                var(resource_type, resource_id, f'elements__{key}'),
                str(val),
            ))

    return lines


def generate_liquid_content(
    resources: List[Tuple[str, str, Dict[str, Any]]],
) -> str:
    """Return the full content of smart.liquid."""
    sections: List[str] = [_FILE_HEADER]

    current_type: Optional[str] = None
    for resource_type, resource_id, resource in resources:
        if resource_type != current_type:
            sections.append(f"\n{{%- comment -%}} === {resource_type} === {{%- endcomment -%}}")
            current_type = resource_type
        assignments = generate_assignments(resource_type, resource_id, resource)
        sections.extend(assignments)

    return "\n".join(sections) + "\n"


def generate_markdown_table(
    resources: List[Tuple[str, str, Dict[str, Any]]],
) -> str:
    """Return the content of smart.liquid.md documentation page."""
    lines: List[str] = [
        "# Smart Liquid Variables",
        "",
        "This page is auto-generated by `input/scripts/generate_smart_liquid.py`.",
        "It lists all Liquid variables available after `{% include smart.liquid %}` is",
        "included in a page, along with their resolved values.",
        "",
        "| Variable | Value |",
        "|---|---|",
    ]

    for resource_type, resource_id, resource in resources:
        page_file = build_page_filename(resource_type, resource_id)
        json_file = build_json_filename(resource_type, resource_id)
        display = get_display(resource)
        canonical_url = resource.get('url', '')

        def row(var_name: str) -> str:
            return f"| {var_name} | {{{{ {var_name} }}}} |"

        lines.append(row(var(resource_type, resource_id, 'url__canonical')))
        lines.append(row(var(resource_type, resource_id, 'url__page')))
        lines.append(row(var(resource_type, resource_id, 'url__json')))
        lines.append(row(var(resource_type, resource_id, 'text__display')))
        lines.append(row(var(resource_type, resource_id, 'link__html')))

        for key in _ELEMENT_KEYS:
            val = resource.get(key)
            if val is not None and isinstance(val, (str, bool, int, float)):
                lines.append(row(var(resource_type, resource_id, f'elements__{key}')))

    lines.append("")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    # -----------------------------------------------------------------------
    # Argument handling
    # -----------------------------------------------------------------------
    output_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("output")
    ig_root = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(".")

    # -----------------------------------------------------------------------
    # DAK IG check – skip entirely if dak.json is absent
    # -----------------------------------------------------------------------
    dak_json_path = ig_root / "dak.json"
    if not dak_json_path.exists():
        print("ℹ️  dak.json not found – this is not a DAK IG. Skipping smart.liquid generation.")
        return 0

    print(f"✅ DAK IG detected (dak.json found at {dak_json_path})")
    print(f"📂 Scanning IG Publisher output: {output_dir}")

    # -----------------------------------------------------------------------
    # Discover resources
    # -----------------------------------------------------------------------
    resources = discover_resources(output_dir)
    print(f"📋 Discovered {len(resources)} resource instance(s) from IG Publisher output")

    if not resources:
        print("⚠️  No resources found in output directory – smart.liquid will be header-only")

    # -----------------------------------------------------------------------
    # Generate input/includes/smart.liquid
    # -----------------------------------------------------------------------
    includes_dir = ig_root / "input" / "includes"
    includes_dir.mkdir(parents=True, exist_ok=True)
    smart_liquid_path = includes_dir / "smart.liquid"

    liquid_content = generate_liquid_content(resources)
    smart_liquid_path.write_text(liquid_content, encoding='utf-8')
    print(f"✅ Generated: {smart_liquid_path}")

    # Echo file to build logs as required
    print("=" * 72)
    print(f"=== BEGIN {smart_liquid_path} ===")
    print(liquid_content)
    print(f"=== END {smart_liquid_path} ===")
    print("=" * 72)

    # -----------------------------------------------------------------------
    # Copy to output/smart.liquid
    # -----------------------------------------------------------------------
    output_smart_liquid_path = output_dir / "smart.liquid"
    if output_dir.is_dir():
        shutil.copy2(smart_liquid_path, output_smart_liquid_path)
        print(f"✅ Copied to: {output_smart_liquid_path}")
    else:
        print(f"⚠️  Output directory does not exist – skipping copy to {output_smart_liquid_path}")

    # -----------------------------------------------------------------------
    # Generate input/pagecontent/smart.liquid.md
    # -----------------------------------------------------------------------
    pagecontent_dir = ig_root / "input" / "pagecontent"
    pagecontent_dir.mkdir(parents=True, exist_ok=True)
    smart_md_path = pagecontent_dir / "smart.liquid.md"

    md_content = generate_markdown_table(resources)
    smart_md_path.write_text(md_content, encoding='utf-8')
    print(f"✅ Generated: {smart_md_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
