#!/usr/bin/env python3
"""
md_to_pot.py - Extract translatable strings from Markdown files into PO/POT format.

Scans input/pagecontent/ for Markdown files and generates:
  - input/translations/messages.pot   (merged template for Weblate)
  - input/translations/<lang>/LC_MESSAGES/messages.po  (per-language stubs)

Supported UN languages: ar, zh, fr, ru, es  (English is the source)

Usage:
    python3 input/scripts/md_to_pot.py [--pagecontent-dir DIR] [--translations-dir DIR]
"""

import argparse
import os
import sys
import re
import datetime
import polib

# The six UN official languages (source = en)
UN_LANGUAGES = ["ar", "zh", "fr", "ru", "es"]

# Files that are auto-generated by the IG publisher and should not be translated
SKIP_PATTERNS = [
    r"^StructureDefinition-",
    r"^ValueSet-",
    r"^ValueSets",
    r"^CodeSystem-",
    r"^ConceptMap-",
    r"^CapabilityStatement-",
]


def should_skip(filename: str) -> bool:
    """Return True if the file is IG-publisher-generated and should not be translated."""
    for pattern in SKIP_PATTERNS:
        if re.match(pattern, filename):
            return True
    return False


def extract_blocks_from_markdown(md_text: str) -> list[str]:
    """
    Return a list of translatable text blocks from a Markdown string.

    A block is defined as a run of non-empty, non-directive lines.
    Liquid/FHIR include directives ({% ... %}) are excluded from extraction
    because they are not human-readable text.
    """
    blocks: list[str] = []
    current: list[str] = []

    for raw_line in md_text.splitlines():
        line = raw_line.rstrip()

        # Skip pure include/directive lines
        if re.match(r"^\{%.*%\}$", line.strip()):
            if current:
                blocks.append("\n".join(current))
                current = []
            continue

        if line:
            current.append(line)
        else:
            if current:
                blocks.append("\n".join(current))
                current = []

    if current:
        blocks.append("\n".join(current))

    # Filter out very short strings (e.g. lone "#" or "---"), pure code fences,
    # and standalone Kramdown/Jekyll attribute blocks like "{: .no_toc}"
    return [
        b
        for b in blocks
        if len(b.strip()) > 1
        and not b.strip().startswith("```")
        and not re.match(r"^\{[:%#]", b.strip())
    ]


def build_pot(md_files: list[tuple[str, str]]) -> polib.POFile:
    """
    Build a POFile (template) from a list of (filepath, md_text) tuples.

    Each unique translatable block becomes one POEntry; occurrences are
    tracked as comment references so translators see where strings come from.
    """
    pot = polib.POFile()
    pot.metadata = {
        "Project-Id-Version": "WHO SMART Base",
        "Report-Msgid-Bugs-To": "https://github.com/WorldHealthOrganization/smart-base/issues",
        "POT-Creation-Date": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M+0000"),
        "MIME-Version": "1.0",
        "Content-Type": "text/plain; charset=UTF-8",
        "Content-Transfer-Encoding": "8bit",
    }
    pot.metadata_is_fuzzy = False

    # msgid -> list of occurrence tuples
    seen: dict[str, list[tuple[str, str]]] = {}

    for filepath, md_text in md_files:
        basename = os.path.basename(filepath)
        blocks = extract_blocks_from_markdown(md_text)
        for block in blocks:
            msgid = block
            if msgid not in seen:
                seen[msgid] = []
            seen[msgid].append((basename, ""))

    for msgid, occurrences in seen.items():
        entry = polib.POEntry(
            msgid=msgid,
            msgstr="",
            occurrences=occurrences,
        )
        pot.append(entry)

    return pot


def update_language_po(lang: str, pot: polib.POFile, translations_dir: str) -> None:
    """
    Create or update the PO file for *lang* from the given POT template.

    Existing translations are preserved; new strings are added as untranslated;
    obsolete strings are removed.
    """
    lang_dir = os.path.join(translations_dir, lang, "LC_MESSAGES")
    os.makedirs(lang_dir, exist_ok=True)
    po_path = os.path.join(lang_dir, "messages.po")

    if os.path.exists(po_path):
        po = polib.pofile(po_path)
    else:
        po = polib.POFile()
        po.metadata = dict(pot.metadata)
        po.metadata["Language"] = lang
        po.metadata["PO-Revision-Date"] = "YEAR-MO-DA HO:MI+ZONE"
        po.metadata["Last-Translator"] = "FULL NAME <EMAIL@ADDRESS>"
        po.metadata["Language-Team"] = f"{lang} <LL@li.org>"
        po.metadata["Plural-Forms"] = "nplurals=2; plural=(n != 1);"
        po.metadata_is_fuzzy = False

    # Build lookup of existing translations
    existing: dict[str, str] = {e.msgid: e.msgstr for e in po}

    new_po = polib.POFile()
    new_po.metadata = po.metadata

    for pot_entry in pot:
        msgstr = existing.get(pot_entry.msgid, "")
        entry = polib.POEntry(
            msgid=pot_entry.msgid,
            msgstr=msgstr,
            occurrences=pot_entry.occurrences,
        )
        new_po.append(entry)

    new_po.save(po_path)
    print(f"  Updated: {po_path} ({len(new_po)} entries)")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract translatable strings from Markdown files into POT/PO format."
    )
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    parser.add_argument(
        "--pagecontent-dir",
        default=os.path.join(repo_root, "input", "pagecontent"),
        help="Directory containing source Markdown files (default: input/pagecontent)",
    )
    parser.add_argument(
        "--translations-dir",
        default=os.path.join(repo_root, "input", "translations"),
        help="Output directory for POT/PO files (default: input/translations)",
    )
    args = parser.parse_args()

    pagecontent_dir: str = args.pagecontent_dir
    translations_dir: str = args.translations_dir

    if not os.path.isdir(pagecontent_dir):
        print(f"ERROR: pagecontent directory not found: {pagecontent_dir}", file=sys.stderr)
        sys.exit(1)

    # Collect markdown files that should be translated
    md_files: list[tuple[str, str]] = []
    for fname in sorted(os.listdir(pagecontent_dir)):
        if not fname.endswith(".md"):
            continue
        if should_skip(fname):
            continue
        fpath = os.path.join(pagecontent_dir, fname)
        with open(fpath, encoding="utf-8") as fh:
            md_files.append((fpath, fh.read()))

    if not md_files:
        print("No translatable Markdown files found.", file=sys.stderr)
        sys.exit(0)

    print(f"Processing {len(md_files)} Markdown file(s) from {pagecontent_dir}")

    # Build the POT template
    pot = build_pot(md_files)

    os.makedirs(translations_dir, exist_ok=True)
    pot_path = os.path.join(translations_dir, "messages.pot")
    pot.save(pot_path)
    print(f"Saved POT template: {pot_path} ({len(pot)} entries)")

    # Update per-language PO files
    for lang in UN_LANGUAGES:
        update_language_po(lang, pot, translations_dir)

    print("Done.")


if __name__ == "__main__":
    main()
