#!/usr/bin/env python3
"""
md_to_pot.py - Extract translatable strings from multiple source types into PO/POT format.

Sources scanned by default:
  Markdown  : input/pages/, input/pagecontent/
  SVG       : input/images/, input/images-src/  (<text>, <title>, <desc> elements)
  PlantUML  : input/images/, input/images-src/  (.plantuml and .uml files —
              title, note blocks, arrow/node labels)

Output:
  input/translations/messages.pot              (merged template for Weblate)
  input/translations/<lang>/LC_MESSAGES/messages.po   (per-language stubs)

Supported UN languages: ar, zh, fr, ru, es  (English is the source)

Usage:
    python3 input/scripts/md_to_pot.py [options]
    python3 input/scripts/md_to_pot.py --source-dir input/pages --source-dir input/pagecontent
"""

import argparse
import os
import re
import sys
import datetime
import xml.etree.ElementTree as ET
import polib

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

UN_LANGUAGES = ["ar", "zh", "fr", "ru", "es"]

# Markdown filename prefixes that are auto-generated by the IG publisher
MD_SKIP_PATTERNS = [
    r"^StructureDefinition-",
    r"^ValueSet-",
    r"^ValueSets",
    r"^CodeSystem-",
    r"^ConceptMap-",
    r"^CapabilityStatement-",
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _is_meaningful(text: str) -> bool:
    """Return True if *text* is worth translating (non-trivial, non-technical)."""
    t = text.strip()
    return (
        len(t) > 1
        and not t.startswith("```")
        and not t.startswith("{%")
        and not re.match(r"^\{[:%#]", t)   # Kramdown attribute lists
        and not re.match(r"^[A-Za-z0-9_./-]+$", t)  # bare identifiers / paths
    )


def _iter_files(directories: list[str], extension: str):
    """Yield (filepath, text) for every *extension* file found in *directories*."""
    for d in directories:
        if not os.path.isdir(d):
            continue
        for root, _, files in os.walk(d):
            for fname in sorted(files):
                if fname.endswith(extension):
                    fpath = os.path.join(root, fname)
                    try:
                        with open(fpath, encoding="utf-8") as fh:
                            yield fpath, fh.read()
                    except (OSError, UnicodeDecodeError):
                        pass


def _should_skip_md(filename: str) -> bool:
    for pattern in MD_SKIP_PATTERNS:
        if re.match(pattern, filename):
            return True
    return False


# ---------------------------------------------------------------------------
# Per-format extractors  →  list[(filepath, msgid)]
# ---------------------------------------------------------------------------

def collect_markdown(source_dirs: list[str]) -> list[tuple[str, str]]:
    """Extract translatable blocks from Markdown files."""
    results: list[tuple[str, str]] = []
    for d in source_dirs:
        if not os.path.isdir(d):
            continue
        for fname in sorted(os.listdir(d)):
            if not fname.endswith(".md") or _should_skip_md(fname):
                continue
            fpath = os.path.join(d, fname)
            try:
                with open(fpath, encoding="utf-8") as fh:
                    text = fh.read()
            except (OSError, UnicodeDecodeError):
                continue
            blocks: list[str] = []
            current: list[str] = []
            for raw_line in text.splitlines():
                line = raw_line.rstrip()
                if re.match(r"^\{%.*%\}$", line.strip()):
                    if current:
                        blocks.append("\n".join(current))
                        current = []
                    continue
                if line:
                    current.append(line)
                else:
                    if current:
                        blocks.append("\n".join(current))
                        current = []
            if current:
                blocks.append("\n".join(current))
            for block in blocks:
                if _is_meaningful(block):
                    results.append((fpath, block))
    return results


def collect_svg(svg_dirs: list[str]) -> list[tuple[str, str]]:
    """Extract <text>, <title>, and <desc> content from SVG files."""
    results: list[tuple[str, str]] = []
    for fpath, text in _iter_files(svg_dirs, ".svg"):
        try:
            root = ET.fromstring(text)
        except ET.ParseError:
            continue
        for elem in root.iter():
            local = elem.tag.split("}")[-1] if "}" in elem.tag else elem.tag
            if local in ("text", "title", "desc") and elem.text:
                value = elem.text.strip()
                if _is_meaningful(value):
                    results.append((fpath, value))
    return results


def collect_plantuml(plantuml_dirs: list[str]) -> list[tuple[str, str]]:
    """Extract translatable strings from PlantUML (.plantuml and .uml) files.

    Extracts:
      - ``title <text>`` directives
      - ``note`` / ``end note`` blocks (single-line and multi-line)
      - Arrow labels:  ``A -> B : label``
      - Node/actor labels in double quotes: ``actor "Label" as x``
      - Package / rectangle / frame labels in double quotes
    """
    results: list[tuple[str, str]] = []

    _title      = re.compile(r"^\s*title\s+(.+)$", re.IGNORECASE)
    _note_sl    = re.compile(
        r"^\s*(?:note|rnote|hnote)\s+"
        r"(?:over\s+\S+\s*:\s*|(?:left|right|top|bottom)\s+of\s+\S+\s*:\s*|(?:left|right)\s*:\s*)(.+)$",
        re.IGNORECASE,
    )
    _arrow      = re.compile(r"(?:->|-->|->>|-->>|<-|<--|<<-|<<--).*?:\s*(.+)$")
    _quoted     = re.compile(r'"([^"]{2,})"')
    _note_start = re.compile(r"^\s*(?:note|rnote|hnote)\b", re.IGNORECASE)
    _note_end   = re.compile(r"^\s*end\s*(?:note|rnote|hnote)\b", re.IGNORECASE)

    for extension in (".plantuml", ".uml"):
        for fpath, text in _iter_files(plantuml_dirs, extension):
            lines = text.splitlines()
            i = 0
            while i < len(lines):
                line = lines[i]
                stripped = line.strip()

                # title
                m = _title.match(stripped)
                if m:
                    value = m.group(1).strip()
                    if _is_meaningful(value):
                        results.append((fpath, value))
                    i += 1
                    continue

                # multi-line note block
                if _note_start.match(stripped) and not _note_sl.match(stripped):
                    note_lines: list[str] = []
                    i += 1
                    while i < len(lines):
                        if _note_end.match(lines[i].strip()):
                            i += 1
                            break
                        note_lines.append(lines[i].strip())
                        i += 1
                    value = "\n".join(note_lines).strip()
                    if _is_meaningful(value):
                        results.append((fpath, value))
                    continue

                # single-line note with inline text
                m = _note_sl.match(stripped)
                if m:
                    value = m.group(1).strip()
                    if _is_meaningful(value):
                        results.append((fpath, value))
                    i += 1
                    continue

                # arrow label
                m = _arrow.search(stripped)
                if m:
                    value = m.group(1).strip()
                    if _is_meaningful(value):
                        results.append((fpath, value))

                # quoted labels (actor, usecase, package, rectangle…)
                for qm in _quoted.finditer(stripped):
                    value = qm.group(1).strip()
                    if _is_meaningful(value):
                        results.append((fpath, value))

                i += 1
    return results


# ---------------------------------------------------------------------------
# POT builder
# ---------------------------------------------------------------------------

def build_pot(sources: list[tuple[str, str]]) -> polib.POFile:
    """Build a POFile template from (filepath, msgid) pairs.

    Duplicate msgids are merged; all source locations are recorded as
    occurrence comments so translators know where each string comes from.
    """
    pot = polib.POFile()
    pot.metadata = {
        "Project-Id-Version": "WHO SMART Base",
        "Report-Msgid-Bugs-To": "https://github.com/WorldHealthOrganization/smart-base/issues",
        "POT-Creation-Date": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M+0000"),
        "MIME-Version": "1.0",
        "Content-Type": "text/plain; charset=UTF-8",
        "Content-Transfer-Encoding": "8bit",
    }
    pot.metadata_is_fuzzy = False

    seen: dict[str, list[tuple[str, str]]] = {}
    for filepath, msgid in sources:
        basename = os.path.basename(filepath)
        seen.setdefault(msgid, [])
        occ = (basename, "")
        if occ not in seen[msgid]:
            seen[msgid].append(occ)

    for msgid, occurrences in seen.items():
        pot.append(polib.POEntry(msgid=msgid, msgstr="", occurrences=occurrences))

    return pot


# ---------------------------------------------------------------------------
# PO updater
# ---------------------------------------------------------------------------

def update_language_po(lang: str, pot: polib.POFile, translations_dir: str) -> None:
    """Create or update the PO file for *lang* from the given POT template.

    Existing translations are preserved; new strings are added as untranslated;
    obsolete strings are removed.
    """
    lang_dir = os.path.join(translations_dir, lang, "LC_MESSAGES")
    os.makedirs(lang_dir, exist_ok=True)
    po_path = os.path.join(lang_dir, "messages.po")

    if os.path.exists(po_path):
        po = polib.pofile(po_path)
    else:
        po = polib.POFile()
        po.metadata = dict(pot.metadata)
        po.metadata["Language"] = lang
        po.metadata["PO-Revision-Date"] = "YEAR-MO-DA HO:MI+ZONE"
        po.metadata["Last-Translator"] = "FULL NAME <EMAIL@ADDRESS>"
        po.metadata["Language-Team"] = f"{lang} <LL@li.org>"
        po.metadata["Plural-Forms"] = "nplurals=2; plural=(n != 1);"
        po.metadata_is_fuzzy = False

    existing: dict[str, str] = {e.msgid: e.msgstr for e in po}

    new_po = polib.POFile()
    new_po.metadata = po.metadata

    for pot_entry in pot:
        entry = polib.POEntry(
            msgid=pot_entry.msgid,
            msgstr=existing.get(pot_entry.msgid, ""),
            occurrences=pot_entry.occurrences,
        )
        new_po.append(entry)

    new_po.save(po_path)
    print(f"  Updated: {po_path} ({len(new_po)} entries)")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    def repo(path: str) -> str:
        return os.path.join(repo_root, path)

    parser = argparse.ArgumentParser(
        description=(
            "Extract translatable strings from Markdown (.md), SVG (.svg), "
            "and PlantUML (.plantuml, .uml) source files into Gettext POT/PO format for Weblate."
        )
    )
    parser.add_argument(
        "--source-dir", dest="source_dirs", metavar="DIR", action="append",
        help="Markdown source directory (repeatable). "
             "Default: input/pages and input/pagecontent",
    )
    parser.add_argument(
        "--svg-dir", dest="svg_dirs", metavar="DIR", action="append",
        help="SVG/PlantUML image directory (repeatable). "
             "Default: input/images and input/images-src",
    )
    parser.add_argument(
        "--translations-dir", default=repo("input/translations"),
        help="Output directory for POT/PO files (default: input/translations)",
    )
    args = parser.parse_args()

    source_dirs      = args.source_dirs or [repo("input/pages"), repo("input/pagecontent")]
    svg_dirs         = args.svg_dirs    or [repo("input/images"), repo("input/images-src")]
    translations_dir: str = args.translations_dir

    # Collect from all sources
    sources: list[tuple[str, str]] = []

    md = collect_markdown(source_dirs)
    print(f"Markdown : {len(md)} strings from {[os.path.basename(d) for d in source_dirs]}")
    sources.extend(md)

    svg = collect_svg(svg_dirs)
    print(f"SVG      : {len(svg)} strings from {[os.path.basename(d) for d in svg_dirs]}")
    sources.extend(svg)

    puml = collect_plantuml(svg_dirs)
    print(f"PlantUML : {len(puml)} strings from {[os.path.basename(d) for d in svg_dirs]}")
    sources.extend(puml)

    if not sources:
        print("No translatable strings found.", file=sys.stderr)
        sys.exit(0)

    pot = build_pot(sources)

    os.makedirs(translations_dir, exist_ok=True)
    pot_path = os.path.join(translations_dir, "messages.pot")
    pot.save(pot_path)
    print(f"\nSaved POT : {pot_path} ({len(pot)} unique entries)")

    for lang in UN_LANGUAGES:
        update_language_po(lang, pot, translations_dir)

    print("Done.")


if __name__ == "__main__":
    main()

