#!/usr/bin/env python3
"""
translation_report.py — Generate a translation completeness report.

Scans all .po files in the repo and produces a Markdown report at
input/pagecontent/translation-status.md showing per-language, per-component
translation completeness percentages.

Usage:
    python translation_report.py [--repo-root .] [--output input/pagecontent/translation-status.md]

Exit codes:
    0  Report generated successfully
    1  Error

Author: WHO SMART Guidelines Team
"""

import argparse
import logging
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

from translation_config import (
    DakConfigError,
    TranslationComponent,
    discover_components,
    get_language_codes,
    load_dak_config,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# PO file statistics
# ---------------------------------------------------------------------------

def _count_po_stats(po_path: Path) -> Tuple[int, int, int]:
    """
    Count msgid entries in a .po file.

    Returns: (total_messages, translated_messages, fuzzy_messages)
    """
    if not po_path.is_file():
        return (0, 0, 0)

    try:
        content = po_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return (0, 0, 0)

    total = 0
    translated = 0
    fuzzy = 0
    is_fuzzy = False

    # Simple PO parser — count msgid/msgstr pairs
    lines = content.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if line.startswith("#,") and "fuzzy" in line:
            is_fuzzy = True

        if line.startswith("msgid "):
            # Skip the header entry (empty msgid at the start)
            msgid_text = line[6:].strip().strip('"')
            # Collect continuation lines
            j = i + 1
            while j < len(lines) and lines[j].strip().startswith('"'):
                msgid_text += lines[j].strip().strip('"')
                j += 1

            if msgid_text:  # Non-empty msgid (skip header)
                total += 1

                # Find corresponding msgstr
                while j < len(lines):
                    sline = lines[j].strip()
                    if sline.startswith("msgstr "):
                        msgstr_text = sline[7:].strip().strip('"')
                        k = j + 1
                        while k < len(lines) and lines[k].strip().startswith('"'):
                            msgstr_text += lines[k].strip().strip('"')
                            k += 1
                        if msgstr_text:
                            if is_fuzzy:
                                fuzzy += 1
                            else:
                                translated += 1
                        break
                    j += 1

            is_fuzzy = False

        i += 1

    return (total, translated, fuzzy)


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_report(
    repo_root: Path,
    output_path: Path,
) -> int:
    """
    Generate translation-status.md report.

    Returns 0 on success, 1 on error.
    """
    try:
        config = load_dak_config(repo_root)
    except DakConfigError:
        logger.warning("dak.json not found — generating minimal report")
        config = None

    components = discover_components(repo_root)
    languages = get_language_codes(config) if config else []

    if not components:
        logger.info("No translation components found")

    if not languages:
        logger.info("No target languages configured")

    # Collect statistics
    # stats[component_slug][lang_code] = (total, translated, fuzzy)
    stats: Dict[str, Dict[str, Tuple[int, int, int]]] = {}

    for comp in components:
        stats[comp.slug] = {}
        for lang in languages:
            po_path = comp.translations_dir / f"{lang}.po"
            stats[comp.slug][lang] = _count_po_stats(po_path)

    # Build Markdown report
    lines: List[str] = []
    lines.append("# Translation Status Report")
    lines.append("")
    lines.append("Auto-generated by `translation_report.py`. Do not edit manually.")
    lines.append("")

    if not components or not languages:
        lines.append("No translation components or languages configured.")
        _write_report(output_path, lines)
        return 0

    # Summary table
    lines.append("## Summary")
    lines.append("")

    # Header row
    header = "| Component |"
    separator = "|-----------|"
    for lang in languages:
        header += f" {lang} |"
        separator += "------|"
    lines.append(header)
    lines.append(separator)

    # Data rows
    for comp in components:
        row = f"| `{comp.slug}` |"
        for lang in languages:
            total, translated, fuzzy = stats[comp.slug].get(lang, (0, 0, 0))
            if total == 0:
                pct = "—"
            else:
                pct_val = (translated / total) * 100
                pct = f"{pct_val:.0f}%"
            row += f" {pct} |"
        lines.append(row)

    lines.append("")

    # Detailed breakdown
    lines.append("## Details")
    lines.append("")

    for comp in components:
        lines.append(f"### {comp.slug}")
        lines.append("")
        lines.append(f"- Template: `{comp.pot_path.relative_to(repo_root)}`")
        lines.append("")
        lines.append("| Language | Total | Translated | Fuzzy | Complete |")
        lines.append("|----------|-------|------------|-------|----------|")

        for lang in languages:
            total, translated, fuzzy = stats[comp.slug].get(lang, (0, 0, 0))
            if total == 0:
                pct = "—"
            else:
                pct = f"{(translated / total) * 100:.1f}%"
            lines.append(
                f"| {lang} | {total} | {translated} | {fuzzy} | {pct} |"
            )

        lines.append("")

    _write_report(output_path, lines)
    return 0


def _write_report(output_path: Path, lines: List[str]) -> None:
    """Write report lines to output path."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("✓ Report written to %s", output_path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
    )

    parser = argparse.ArgumentParser(
        prog="translation_report.py",
        description="Generate translation completeness report",
    )
    parser.add_argument(
        "--repo-root", default=".",
        help="Repository root (default: current directory)",
    )
    parser.add_argument(
        "--output", default="input/pagecontent/translation-status.md",
        help="Output path for the report (default: input/pagecontent/translation-status.md)",
    )
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    output_path = repo_root / args.output

    return generate_report(repo_root, output_path)


if __name__ == "__main__":
    sys.exit(main())
