#!/usr/bin/env python3
"""Update README.md and post-process output/history.html with feature branch build links.

Runs as part of the GitHub Pages build process to keep the repository README
and the CI history page in sync with the current set of deployed feature branches.

Actions performed
-----------------
1. Fetch the list of deployed feature branch directories from the gh-pages branch
   via the GitHub REST API.
2. Post-process the existing ``output/history.html`` generated by the IG Publisher,
   injecting (or replacing) a "CI Feature Branch Builds" section listing all
   currently deployed feature branches with direct links.
   If the file does not exist the step is silently skipped.
3. Update the ``## Publication`` section of ``README.md``, replacing the block
   between ``<!-- CI_BUILD_LINKS_START -->`` and ``<!-- CI_BUILD_LINKS_END -->``
   with current build URLs and a sorted table of feature branch links.
   README.md is only written when its content actually changes (idempotent).

Environment variables
---------------------
GITHUB_REPOSITORY   ``owner/repo`` — always set by GitHub Actions.
GITHUB_TOKEN        Workflow token — optional, reduces API rate-limit risk.
README_UPDATE       Set to ``false`` to skip the README.md update step.

Usage
-----
python3 input/scripts/update_branch_index.py
"""

import html
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_env(name: str) -> str:
    return os.environ.get(name, "").strip()


def _github_api(path: str, token: str = "") -> "list | dict | None":
    """Call the GitHub REST API and return parsed JSON, or None on error."""
    url = f"https://api.github.com/{path.lstrip('/')}"
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    try:
        req = Request(url, headers=headers)
        with urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except HTTPError as exc:
        if exc.code == 404:
            print(f"ℹ️  GitHub API 404 (gh-pages/branches not yet deployed?): {url}")
            return None
        print(f"⚠️  GitHub API HTTP {exc.code}: {url}", file=sys.stderr)
        return None
    except URLError as exc:
        print(f"⚠️  GitHub API network error: {exc}", file=sys.stderr)
        return None


def _fetch_deployed_branches(repo: str, token: str) -> "list[str]":
    """Return sorted list of branch directory names deployed under gh-pages/branches/."""
    data = _github_api(f"repos/{repo}/contents/branches?ref=gh-pages", token)
    if not data or not isinstance(data, list):
        return []
    return sorted(
        item["name"]
        for item in data
        if isinstance(item, dict) and item.get("type") == "dir"
    )


def _load_dak_json(root: Path) -> dict:
    dak_path = root / "dak.json"
    if dak_path.exists():
        try:
            return json.loads(dak_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, IOError):
            pass
    return {}


# ---------------------------------------------------------------------------
# Post-process output/history.html
# ---------------------------------------------------------------------------

# Unique comment marker so the injected block can be replaced on re-runs.
_SECTION_START = "<!-- ci-branch-builds-start -->"
_SECTION_END   = "<!-- ci-branch-builds-end -->"

_SECTION_RE = re.compile(
    re.escape(_SECTION_START) + r".*?" + re.escape(_SECTION_END),
    re.DOTALL,
)

_SECTION_STYLE = (
    "margin-top:2rem;padding:1rem 1.5rem;"
    "border:1px solid #cce5ff;border-radius:.25rem;background:#e8f4fd;"
)
_TABLE_STYLE = (
    "border-collapse:collapse;width:100%;margin-top:.75rem;font-size:.9rem;"
)
_TH_STYLE = (
    "text-align:left;padding:.4rem .6rem;"
    "border:1px solid #b8daff;background:#cce5ff;"
)
_TD_STYLE = "text-align:left;padding:.4rem .6rem;border:1px solid #b8daff;"
_LINK_STYLE = "color:#004085;"


def _branch_rows_html(branches: "list[str]", ci_base: str) -> str:
    if not branches:
        return "<p><em>No feature branches are currently deployed.</em></p>"
    rows = [
        f'    <tr>'
        f'<th style="{_TH_STYLE}">Branch</th>'
        f'<th style="{_TH_STYLE}">CI Build URL</th>'
        f'</tr>'
    ]
    for name in branches:
        url = f"{ci_base.rstrip('/')}/branches/{name}/"
        name_esc = html.escape(name)
        url_esc  = html.escape(url)
        rows.append(
            f'    <tr>'
            f'<td style="{_TD_STYLE}"><code>{name_esc}</code></td>'
            f'<td style="{_TD_STYLE}"><a href="{url_esc}" style="{_LINK_STYLE}">{url_esc}</a></td>'
            f'</tr>'
        )
    return f'<table style="{_TABLE_STYLE}">\n' + "\n".join(rows) + "\n  </table>"


def _build_section_html(branches: "list[str]", ci_base: str) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    rows = _branch_rows_html(branches, ci_base)
    return (
        f"{_SECTION_START}\n"
        f'<div style="{_SECTION_STYLE}">\n'
        f"  <h2>CI Feature Branch Builds</h2>\n"
        f"  <p>The following feature branches are currently deployed to the CI build site.</p>\n"
        f"  {rows}\n"
        f'  <p style="font-size:.8rem;color:#666;margin-top:.5rem;">Updated: {html.escape(ts)}</p>\n'
        f"</div>\n"
        f"{_SECTION_END}"
    )


def _create_standalone_history_html(
    history_path: Path,
    branches: "list[str]",
    ci_base: str,
    title: str,
) -> None:
    """Create a minimal history.html using the IG's own CSS (no package-list.json needed)."""
    section = _build_section_html(branches, ci_base)
    page = (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="utf-8"/>\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>\n'
        f"  <title>CI Build History - {html.escape(title)}</title>\n"
        '  <link href="fhir.css" rel="stylesheet"/>\n'
        '  <link href="assets/css/bootstrap-fhir.css" rel="stylesheet"/>\n'
        '  <link href="assets/css/project.css" rel="stylesheet"/>\n'
        '  <link href="assets/css/who.css" rel="stylesheet"/>\n'
        "</head>\n"
        "<body>\n"
        '  <div class="container">\n'
        f"    <h1>CI Build History &mdash; {html.escape(title)}</h1>\n"
        "    <p>This page lists all feature branch CI builds currently deployed to GitHub Pages.</p>\n"
        f"    <p><a href=\"index.html\">\u2190 Back to {html.escape(title)}</a></p>\n"
        f"    {section}\n"
        "  </div>\n"
        "</body>\n"
        "</html>\n"
    )
    history_path.write_text(page, encoding="utf-8")
    print(f"✅ Created standalone {history_path} (no IG Publisher history.html found).")


def update_history_html(
    history_path: Path,
    branches: "list[str]",
    ci_base: str,
    title: str = "",
) -> None:
    """Inject / replace the CI branch-builds section in history.html.

    If history.html was not generated by the IG Publisher (e.g. no package-list.json),
    a standalone page is created from scratch using the IG's own CSS files.
    """
    if not history_path.exists():
        _create_standalone_history_html(history_path, branches, ci_base, title or "IG")
        return

    original = history_path.read_text(encoding="utf-8")
    section  = _build_section_html(branches, ci_base)

    if _SECTION_START in original:
        # Replace the existing injected section
        updated = _SECTION_RE.sub(section, original, count=1)
    else:
        # Insert just before </body>
        end_body = re.search(r"</body>", original, re.IGNORECASE)
        if end_body:
            pos     = end_body.start()
            updated = original[:pos] + "\n" + section + "\n" + original[pos:]
        else:
            updated = original + "\n" + section + "\n"

    if updated == original:
        print("ℹ️  history.html CI section already up-to-date.")
        return

    history_path.write_text(updated, encoding="utf-8")
    print(f"✅ Post-processed {history_path} with CI branch builds section.")


# ---------------------------------------------------------------------------
# README.md
# ---------------------------------------------------------------------------

_MARKERS_RE = re.compile(
    r"<!-- CI_BUILD_LINKS_START -->.*?<!-- CI_BUILD_LINKS_END -->",
    re.DOTALL,
)


def _branch_table_md(branches: "list[str]", ci_base: str) -> str:
    if not branches:
        return "_No feature branches deployed yet._\n"
    lines = ["| Branch | Build |", "|--------|-------|"]
    for name in branches:
        url = f"{ci_base.rstrip('/')}/branches/{name}/"
        lines.append(f"| `{name}` | [{url}]({url}) |")
    return "\n".join(lines) + "\n"


def _build_marker_block(branches: "list[str]", ci_url: str, pub_url: str) -> str:
    branch_md = _branch_table_md(branches, ci_url)
    return (
        "<!-- CI_BUILD_LINKS_START -->\n"
        f"Continuous Build: [{ci_url}]({ci_url})  \n"
        f"Published: [{pub_url}]({pub_url})\n\n"
        "### Feature Branch Builds\n"
        f"{branch_md}"
        "<!-- CI_BUILD_LINKS_END -->"
    )


def update_readme(
    readme_path: Path,
    branches: "list[str]",
    ci_url: str,
    pub_url: str,
) -> bool:
    """Replace the marker block in README.md.  Return True if the file changed."""
    if not readme_path.exists():
        print(f"⚠️  README.md not found at {readme_path}", file=sys.stderr)
        return False

    original = readme_path.read_text(encoding="utf-8")

    if "<!-- CI_BUILD_LINKS_START -->" not in original:
        print(
            "⚠️  README.md does not contain CI_BUILD_LINKS markers — skipping update.\n"
            "    Add <!-- CI_BUILD_LINKS_START --> and <!-- CI_BUILD_LINKS_END --> markers\n"
            "    inside the ## Publication section to enable automatic updates.",
            file=sys.stderr,
        )
        return False

    new_block = _build_marker_block(branches, ci_url, pub_url)
    updated   = _MARKERS_RE.sub(new_block, original, count=1)

    if updated == original:
        print("ℹ️  README.md Publication links are already up-to-date.")
        return False

    readme_path.write_text(updated, encoding="utf-8")
    print("✅ Updated README.md Publication section with current branch build links.")
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    repo         = _read_env("GITHUB_REPOSITORY")
    token        = _read_env("GITHUB_TOKEN")
    skip_readme  = _read_env("README_UPDATE").lower() == "false"

    root = Path(".")
    dak  = _load_dak_json(root)

    title = dak.get("title") or (repo.split("/")[-1] if repo else "IG")

    if repo:
        owner, repo_name = repo.split("/", 1)
        ci_base = dak.get("previewUrl") or f"https://{owner}.github.io/{repo_name}"
        pub_url = dak.get("publicationUrl") or ci_base
    else:
        ci_base = "https://worldhealthorganization.github.io/smart-base"
        pub_url = ci_base

    ci_base = ci_base.rstrip("/")

    # Fetch deployed feature branches from gh-pages/branches/
    branches: "list[str]" = []
    if repo:
        branches = _fetch_deployed_branches(repo, token)
        if branches:
            print(f"Found {len(branches)} deployed branch(es): {', '.join(branches)}")
        else:
            print("No feature branches found on gh-pages yet.")

    # 1. Post-process output/history.html (IG Publisher generates this file).
    # If the IG Publisher did not create it (e.g. no package-list.json), a
    # standalone page is generated so the URL never returns 404.
    update_history_html(root / "output" / "history.html", branches, ci_base, title)

    # 2. Update README.md (only when the markers are present and content changed)
    if not skip_readme:
        changed = update_readme(root / "README.md", branches, ci_base, pub_url)
        print("README_CHANGED=true" if changed else "README_CHANGED=false")
    else:
        print("ℹ️  README_UPDATE=false — skipping README.md update.")


if __name__ == "__main__":
    main()
