# FHIR IG Build and Deploy Workflow (Combined)
# This workflow calls both build-only and deploy-only workflows in sequence
# Equivalent to: v2-ghbuildonly.yml + v2-ghdeployonly.yml
# Based on the idea by Carl Leitner
# Change log:
# 2021-06-18: (JCT): publish default branches to / , other branches branches/<branch>
# 2021-11-26: (JCT): Reusable workflow
# 2022-01-28: (JCT): add auto-create gh-pages if it doesn't exist
# 2023-01-22: (JCT): use checkout action v3, and JamesIves/github-pages-deploy-action@v4
# 2024-XX-XX: (v2): Combined workflow calling build-only and deploy-only workflows

name: Build and Deploy

# Controls when the action will run. 
on: 
  workflow_call: # Reusable by other workflows
    inputs:
      tx:
        required: false
        type: string
  # This is a called workflow - it should not trigger directly on push/pull_request
  # The main dakbuild.yml wrapper or other workflows call this workflow

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tx:
        description: 'Optional Custom terminology server URL'
        required: false

# Prevent concurrent deployments to avoid race conditions when updating gh-pages branch
concurrency:
  group: gh-pages-deployment-${{ github.ref }}
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build phase - calls build-only workflow
  build:
    uses: ./.github/workflows/v2-ghbuildonly.yml
    with:
      tx: ${{ inputs.tx }}
    secrets: inherit

  # Deploy phase - calls deploy-only workflow
  deploy:
    needs: build
    uses: ./.github/workflows/v2-ghdeployonly.yml
    with:
      artifact_name: ig-build-output
    secrets: inherit