# DAK (Data Access Kit) Build Workflow
# Main entry point for DAK builds with all DAK-specific features
# This workflow calls v2-dakbuild.yml with all the necessary parameters

name: DAK Build

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events for any branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tx:
        description: 'Optional Custom terminology server URL'
        required: false
      generate_dmn_questionnaires:
        description: 'Generate DMN Questionnaires'
        required: false
        type: boolean
        default: true
      transform_dmn_files:
        description: 'Transform DMN files to HTML'
        required: false
        type: boolean
        default: true
      generate_valueset_schemas:
        description: 'Generate ValueSet JSON Schemas'
        required: false
        type: boolean
        default: true
      generate_logical_model_schemas:
        description: 'Generate Logical Model JSON Schemas'
        required: false
        type: boolean
        default: true
      generate_dak_api_hub:
        description: 'Generate DAK API Documentation Hub'
        required: false
        type: boolean
        default: true
      generate_jsonld_vocabularies:
        description: 'Generate JSON-LD Vocabularies from ValueSet expansions'
        required: false
        type: boolean
        default: true

# Prevent concurrent deployments to avoid race conditions when updating gh-pages branch
concurrency:
  group: dak-deployment-${{ github.ref }}
  cancel-in-progress: false

# A workflow run is made up of one or more jobs
jobs:
  # Call the v2 DAK workflow with all the DAK-specific parameters
  call-v2-dakbuild:
    name: Build and Deploy with DAK Features
    uses: ./.github/workflows/v2-dakbuild.yml
    with:
      tx: ${{ inputs.tx }}
      generate_dmn_questionnaires: ${{ inputs.generate_dmn_questionnaires }}
      transform_dmn_files: ${{ inputs.transform_dmn_files }}
      generate_valueset_schemas: ${{ inputs.generate_valueset_schemas }}
      generate_logical_model_schemas: ${{ inputs.generate_logical_model_schemas }}
      generate_dak_api_hub: ${{ inputs.generate_dak_api_hub }}
      generate_jsonld_vocabularies: ${{ inputs.generate_jsonld_vocabularies }}
    secrets: inherit