# Wrapper workflow that calls the v1-ghbuild for backward compatibility
# The current workflow functionality has been moved to v1-ghbuild.yml
# For new projects, consider using:
# - v2-ghbuild.yml for standard FHIR IG builds
# - v2-dakbuild.yml for builds with DAK features
# 
# This wrapper ensures existing references to ghbuild.yml continue to work

name: CI (v1 - Legacy)

# Controls when the action will run. 
on:
  workflow_call: # Reusable by other workflows
    inputs:
      tx:
        required: false
        type: string
  # Triggers the workflow on push or pull request events for any branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tx:
        description: 'Optional Custom terminology server URL'
        required: false

# Prevent concurrent deployments to avoid race conditions when updating gh-pages branch
concurrency:
  group: gh-pages-deployment-${{ github.ref }}
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Call the v1 workflow for backward compatibility
  call-v1-ghbuild:
    name: Build and Deploy (v1 Legacy)
    uses: ./.github/workflows/v1-ghbuild.yml
    with:
      tx: ${{ inputs.tx }}
    secrets: inherit
