# Wrapper workflow that calls the v1 ghbuild for backward compatibility
# The current workflow functionality has been moved to v1/ghbuild.yml
# For new projects, consider using:
# - v2/ghbuild.yml for standard FHIR IG builds
# - v2/dakbuild.yml for builds with DAK features
# 
# This wrapper ensures existing references to ghbuild.yml continue to work

name: CI (v1 - Legacy)

# Controls when the action will run. 
on: 
  workflow_call: # Reusable by other workflows
    inputs:
      tx:
        required: false
        type: string
  # Triggers the workflow on push or pull request events for any branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tx:
        description: 'Optional Custom terminology server URL'
        required: false
      generate_dmn_questionnaires:
        description: 'Generate DMN Questionnaires (default: enabled for WHO repos, disabled for others)'
        required: false
        type: boolean
      transform_dmn_files:
        description: 'Transform DMN files to HTML (default: enabled for WHO repos, disabled for others)'
        required: false
        type: boolean
      generate_valueset_schemas:
        description: 'Generate ValueSet JSON Schemas (default: enabled for WHO repos, disabled for others)'
        required: false
        type: boolean
      generate_logical_model_schemas:
        description: 'Generate Logical Model JSON Schemas (default: enabled for WHO repos, disabled for others)'
        required: false
        type: boolean
      generate_dak_api_hub:
        description: 'Generate DAK API Documentation Hub (default: enabled for WHO repos, disabled for others)'
        required: false
        type: boolean
      generate_jsonld_vocabularies:
        description: 'Generate JSON-LD Vocabularies from ValueSet expansions (default: enabled for WHO repos, disabled for others)'
        required: false
        type: boolean

# Prevent concurrent deployments to avoid race conditions when updating gh-pages branch
concurrency:
  group: github-pages-deployment
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Call the v1 workflow for backward compatibility
  call-v1-ghbuild:
    uses: ./.github/workflows/v1/ghbuild.yml
    with:
      tx: ${{ inputs.tx }}
      generate_dmn_questionnaires: ${{ inputs.generate_dmn_questionnaires }}
      transform_dmn_files: ${{ inputs.transform_dmn_files }}
      generate_valueset_schemas: ${{ inputs.generate_valueset_schemas }}
      generate_logical_model_schemas: ${{ inputs.generate_logical_model_schemas }}
      generate_dak_api_hub: ${{ inputs.generate_dak_api_hub }}
      generate_jsonld_vocabularies: ${{ inputs.generate_jsonld_vocabularies }}
    secrets: inherit
